apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app3
  description: test
  annotations:
    circleci.com/project-slug: 'github/wonjoyoo/nginx'
    backstage.io/kubernetes-id: app3
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: production
